### OneHotEncoding


In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df=pd.DataFrame({
    "color": ["red", "blue", "green", "red", "blue"]
})

In [4]:
df.head()

color
0    red
1   blue
2  green
3    red
4   blue

In [5]:
encoder=OneHotEncoder()

In [6]:
encoded=encoder.fit_transform(df[["color"]]).toarray()

In [7]:
import pandas as pd
encoded=pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["color"]))

In [8]:
encoded

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [9]:
pd.concat([df, encoded], axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

### Level Encoding

In [10]:
df.head()

color
0    red
1   blue
2  green
3    red
4   blue

In [11]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [12]:
lbl_encoder.fit_transform(df["color"])

array([2, 0, 1, 2, 0])

In [13]:
lbl_encoder.transform([["red"]])

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

### Ordinal Encoding

In [15]:
from sklearn.preprocessing import OrdinalEncoder


In [17]:
df=pd.DataFrame({
    "size": ["S", "M", "L", "XL", "S"]
})

In [19]:
df

size
0    S
1    M
2    L
3   XL
4    S

In [20]:
encoder=OrdinalEncoder(categories=[["S", "M", "L", "XL"]])
encoded=encoder.fit_transform(df[["size"]])
encoded

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.]])

In [23]:
encoded.tranfrom([["M"]])

AttributeError: 'numpy.ndarray' object has no attribute 'tranfrom'

### Target Guided Ordinal Encoding

In [29]:
import pandas as pd
df=pd.DataFrame({
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix","New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "price": [100, 150, 120, 130, 110, 105, 155, 125, 135, 115]
})


In [30]:
df

city  price
0     New York    100
1  Los Angeles    150
2      Chicago    120
3      Houston    130
4      Phoenix    110
5     New York    105
6  Los Angeles    155
7      Chicago    125
8      Houston    135
9      Phoenix    115

In [32]:
mean_price=df.groupby("city")["price"].mean().to_dict()

In [33]:
mean_price

{'Chicago': 122.5,
 'Houston': 132.5,
 'Los Angeles': 152.5,
 'New York': 102.5,
 'Phoenix': 112.5}

In [34]:
df["city_encoded"]=df["city"].map(mean_price)

In [36]:
df

city  price  city_encoded
0     New York    100         102.5
1  Los Angeles    150         152.5
2      Chicago    120         122.5
3      Houston    130         132.5
4      Phoenix    110         112.5
5     New York    105         102.5
6  Los Angeles    155         152.5
7      Chicago    125         122.5
8      Houston    135         132.5
9      Phoenix    115         112.5

In [39]:
df[['price', 'city_encoded']]

price  city_encoded
0    100         102.5
1    150         152.5
2    120         122.5
3    130         132.5
4    110         112.5
5    105         102.5
6    155         152.5
7    125         122.5
8    135         132.5
9    115         112.5