In [18]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
arrr=arr.reshape(5,1)
print(arrr) 


[1 2 3 4 5]
(5,)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
arr=list(map(lambda x:x**2,arr))
print(np.array(arr))
arrr=arrr.reshape(5,)
print(arrr)
ar=arr+arrr
print(np.array(ar))
arr=np.concatenate((arr,arrr))
print(arr)
loc=(np.where(arr==25))
print(np.array(loc))

[ 1  4  9 16 25]
[1 2 3 4 5]
[ 2  6 12 20 30]
[ 1  4  9 16 25  1  2  3  4  5]
[[4]]


In [45]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [48]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
arr =np.array([[1, 2, 3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [65]:
arr=np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr)) 
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.power(arr,2))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 1  4  9 16 25]


In [ ]:
arr =np.array([[1, 2, 3],[4,5,6]])
print(arr[0:1,0:2])

[[1 2]
 [4 5]]


In [79]:
#Normalization
data=np.array([1, 2, 3, 4, 5])

mean=np.mean(data)
print(mean)
std=np.std(data)
print(std)
normalized_data=(data-mean)/std
print(normalized_data)
median=np.median(data)
print(median)
variance=np.var(data)
print(variance)



3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
2.0


In [80]:
data=np.array([1, 2, 3, 4, 5])
for i in range(len(data)):
    if data[i]>3 and data[i]<5:
        print(data[i])

4


In [86]:
data=np.array([1, 2, 3, 4, 5])
arr=data[(data>3) & (data<5)]
print(arr)

[4]
